"""Bảng dữ liệu (lexicon) tách khỏi app.py — THUẦN DỮ LIỆU, không có logic.

Gom các từ điển tra cứu triệu chứng/nhóm thuốc/hướng dẫn để app.py gọn hơn.
app.py import lại các tên này nên mọi tham chiếu cũ (kể cả scripts dùng
`app.<TÊN_BẢNG>`) vẫn hoạt động như trước.
"""

DRUG_GROUP_GUIDANCE = {
    "thuốc điều trị sốt rét": {
        "treatment": [
            "Hướng xử trí tham khảo: sốt thành cơn kèm rét run sau khi tới vùng lưu hành sốt rét cần được XÉT NGHIỆM (lam máu/test nhanh) để chẩn đoán; KHÔNG tự mua thuốc điều trị sốt rét.",
            "Thuốc điều trị sốt rét phải do bác sĩ chỉ định đúng loại/liều theo chủng ký sinh trùng; tự dùng có thể nguy hiểm và gây kháng thuốc.",
        ],
        "precautions": [
            "Đi khám sớm; sốt rét có thể diễn tiến nặng (sốt rét ác tính) nếu chậm điều trị. Báo bác sĩ nơi đã đi, số ngày sốt, tính chất cơn sốt.",
        ],
        "care": [
            "Bù nước, hạ sốt cơ học, theo dõi tri giác và các dấu hiệu nặng (lơ mơ, vàng da, tiểu ít, co giật) để đi cấp cứu kịp thời.",
        ],
        "warning": "Đây chỉ là gợi ý hướng bệnh, KHÔNG phải đơn thuốc. Nghi sốt rét cần đi khám và xét nghiệm máu sớm; không tự dùng thuốc điều trị sốt rét. Đến cơ sở y tế ngay nếu sốt cao liên tục, lơ mơ, vàng da, tiểu ít hoặc co giật.",
    },
    "vitamin và khoáng chất": {
        "treatment": [
            "Hướng xử trí tham khảo: mệt mỏi kèm da/niêm nhợt và móng giòn gợi ý thiếu máu/thiếu vi chất; cần XÉT NGHIỆM MÁU để xác định nguyên nhân (thiếu sắt, B12/folate, mất máu...) trước khi bổ sung.",
            "Không tự ý bổ sung sắt/vitamin liều cao kéo dài khi chưa rõ nguyên nhân; bổ sung sai loại có thể che lấp bệnh nền.",
        ],
        "precautions": [
            "Đi khám nếu mệt nhiều, khó thở, tim đập nhanh, ngất, phân đen hoặc kinh nguyệt ra nhiều — có thể là thiếu máu nặng hoặc đang mất máu cần xử trí.",
        ],
        "care": [
            "Ăn uống đủ chất (thịt đỏ, rau xanh đậm, đậu), theo dõi mức độ mệt/chóng mặt và ghi lại để cung cấp khi đi khám.",
        ],
        "warning": "Đây chỉ là gợi ý hướng bệnh, KHÔNG phải đơn thuốc. Nghi thiếu máu cần đi khám và xét nghiệm máu để tìm nguyên nhân; không tự bổ sung sắt/vitamin liều cao khi chưa rõ nguyên nhân. Đi khám ngay nếu mệt nhiều, khó thở, ngất hoặc có dấu hiệu mất máu.",
    },
    "thuốc kháng viêm không steroid": {
        "treatment": [
            "Hướng xử trí tham khảo: nhóm thuốc kháng viêm không steroid thường chỉ phù hợp khi có đau/viêm rõ và cần loại trừ nguy cơ dạ dày, thận, tim mạch hoặc thuốc chống đông.",
            "Không tự phối nhiều thuốc giảm đau/kháng viêm cùng lúc; kiểm tra hoạt chất trùng lặp trong thuốc cảm, thuốc đau đầu hoặc thuốc xương khớp.",
        ],
        "precautions": [
            "Tránh tự dùng nếu từng loét/xuất huyết dạ dày, bệnh thận, bệnh tim mạch nặng, đang dùng thuốc chống đông/kháng tiểu cầu, đang mang thai hoặc dị ứng NSAID.",
        ],
        "care": [
            "Nghỉ ngơi, uống đủ nước, theo dõi mức độ đau, yếu tố khởi phát và các dấu hiệu đi kèm như sốt, nôn, nhìn mờ, yếu liệt.",
        ],
    },
    "thuốc giảm đau hạ sốt": {
        "treatment": [
            "Hướng xử trí tham khảo: nhóm giảm đau - hạ sốt có thể được cân nhắc cho đau/sốt nhẹ, nhưng cần kiểm tra bệnh gan, uống rượu nhiều hoặc thuốc đang dùng.",
            "Không dùng nhiều sản phẩm cùng chứa hoạt chất giảm đau/hạ sốt để tránh quá liều ngoài ý muốn.",
        ],
        "precautions": [
            "Đi khám nếu sốt cao kéo dài, đau dữ dội, phát ban, cứng cổ, lơ mơ, khó thở hoặc triệu chứng nặng lên nhanh.",
        ],
        "care": [
            "Nghỉ ở nơi yên tĩnh, bù nước, theo dõi nhiệt độ và ghi lại thời điểm dùng thuốc nếu có dùng.",
        ],
    },
    "thuốc kháng histamin": {
        "treatment": [
            "Hướng xử trí tham khảo: khi hắt hơi, sổ mũi/nghẹt mũi và không sốt, hệ thống ưu tiên hướng viêm mũi dị ứng hoặc cảm lạnh không sốt thay vì thuốc hạ sốt.",
            "Nhóm kháng histamin thường phù hợp hơn với hắt hơi, sổ mũi, ngứa, nổi mề đay hoặc chảy nước mắt; nếu nghẹt mũi là triệu chứng chính, cần cân nhắc thêm chăm sóc/xịt rửa mũi hoặc nhóm thông mũi theo tư vấn dược sĩ/bác sĩ.",
        ],
        "precautions": [
            "Một số thuốc kháng histamin có thể gây buồn ngủ, chóng mặt; tránh lái xe, uống rượu hoặc phối với thuốc an thần khi chưa được tư vấn.",
            "Không tự phối nhiều thuốc cảm/dị ứng cùng lúc vì có thể trùng hoạt chất kháng histamin hoặc thông mũi.",
        ],
        "care": [
            "Tránh tác nhân nghi dị ứng, rửa mũi bằng nước muối sinh lý nếu nghẹt/sổ mũi, theo dõi phát ban hoặc khó thở.",
        ],
    },
    "thuốc thần kinh/tâm thần": {
        "treatment": [
            "Hướng xử trí tham khảo: nhóm thuốc thần kinh/tâm thần cần bác sĩ đánh giá trực tiếp, không tự dùng theo mô tả triệu chứng.",
        ],
        "precautions": [
            "Đi khám sớm nếu mất ngủ kéo dài, lo âu nặng, ý nghĩ tự hại, lú lẫn, co giật, yếu/liệt hoặc đau đầu bất thường.",
        ],
        "care": [
            "Giữ lịch ngủ đều, tránh caffeine/rượu trước khi ngủ, ghi lại thời gian mất ngủ và yếu tố kích hoạt.",
        ],
    },
    "bù dịch và điện giải": {
        "treatment": [
            "Hướng xử trí tham khảo: ưu tiên bù nước và điện giải khi có tiêu chảy, nôn, sốt hoặc dấu hiệu mất nước.",
        ],
        "precautions": [
            "Đi khám nếu nôn không kiểm soát, tiểu ít, khát nhiều, lừ đừ, phân máu, đau bụng dữ dội hoặc người bệnh là trẻ nhỏ/người già.",
        ],
        "care": [
            "Uống từng ngụm nhỏ, ăn nhẹ, tránh rượu bia và theo dõi lượng nước tiểu.",
        ],
    },
    "thuốc chống nôn": {
        "treatment": [
            "Hướng xử trí tham khảo: nếu buồn nôn/nôn, ưu tiên bù nước từng ngụm nhỏ và theo dõi dấu hiệu mất nước.",
            "Nhóm thuốc chống nôn chỉ nên dùng theo tư vấn bác sĩ/dược sĩ, đặc biệt ở trẻ em, người già, phụ nữ mang thai hoặc người có bệnh tim mạch.",
        ],
        "precautions": [
            "Đi khám nếu nôn liên tục, không uống được nước, đau bụng dữ dội, lừ đừ, sốt cao, phân máu hoặc dấu hiệu mất nước.",
        ],
        "care": [
            "Ăn nhẹ, chia nhỏ bữa, tránh rượu bia và thức ăn nhiều dầu mỡ trong giai đoạn còn nôn/buồn nôn.",
        ],
    },
    "thuốc điều trị dạ dày": {
        "treatment": [
            "Hướng xử trí tham khảo: đau thượng vị/ợ chua/nóng rát dạ dày có thể liên quan rối loạn dạ dày - trào ngược; cần đánh giá thêm bữa ăn, thuốc đang dùng và dấu hiệu cảnh báo.",
        ],
        "precautions": [
            "Đi khám nếu đau bụng dữ dội, nôn ra máu, đi ngoài phân đen, sụt cân, nuốt nghẹn hoặc đau kéo dài/tái diễn.",
        ],
        "care": [
            "Ăn nhẹ, tránh rượu bia, cà phê, đồ cay/chua nhiều và không nằm ngay sau ăn.",
        ],
    },
    "thuốc long đờm / giảm ho": {
        "treatment": [
            "Hướng xử trí tham khảo: nếu ho có đờm, ưu tiên uống đủ nước, làm ẩm không khí và chỉ cân nhắc nhóm long đờm/giảm ho theo tư vấn dược sĩ hoặc bác sĩ.",
            "Không tự phối nhiều thuốc ho/cảm cùng lúc vì dễ trùng hoạt chất hoặc làm nặng buồn ngủ, chóng mặt.",
        ],
        "precautions": [
            "Không tự dùng thuốc ức chế ho nếu ho có nhiều đờm, khó thở, đau ngực, sốt cao hoặc nghi nhiễm trùng hô hấp dưới.",
        ],
        "care": [
            "Theo dõi màu đờm, lượng đờm, sốt, khó thở và thời gian ho kéo dài.",
        ],
    },
    "thuốc giảm đau nha khoa": {
        "treatment": [
            "Hướng xử trí tham khảo: đau răng/sưng nướu thường cần khám nha khoa để tìm nguyên nhân như sâu răng, viêm nướu hoặc áp-xe răng.",
            "Có thể cân nhắc nhóm giảm đau thông thường theo tư vấn dược sĩ/bác sĩ; không tự dùng kháng sinh nếu chưa được chỉ định.",
        ],
        "precautions": [
            "Không chườm nóng vùng sưng, không tự chích/rạch nướu và không tự dùng kháng sinh còn dư.",
            "Đi khám nha khoa sớm nếu sưng nướu/mặt, đau tăng, khó há miệng, sốt, hôi miệng nặng hoặc nuốt/ thở khó.",
        ],
        "care": [
            "Súc miệng nhẹ bằng nước ấm, vệ sinh răng miệng, tránh nhai bên đau và tránh thức ăn quá nóng/lạnh/ngọt nếu làm đau tăng.",
        ],
        "warning": "Đau răng kèm sưng nướu cần khám nha khoa để xử lý nguyên nhân. Đi khám sớm nếu sưng mặt, sốt, chảy mủ, khó há miệng, nuốt khó, thở khó hoặc đau tăng nhanh.",
    },
}

RULE_MEDICATION_NAMES = {
    "thuốc giảm đau hạ sốt": "Acetaminophen/Paracetamol; Ibuprofen (tham khảo, cần kiểm tra chống chỉ định)",
    "thuốc long đờm / giảm ho": "Thuốc long đờm hoặc giảm ho phù hợp loại ho (cần dược sĩ/bác sĩ tư vấn)",
    "bù dịch và điện giải": "Dung dịch bù nước điện giải; Oral rehydration salts (ORS)",
    "thuốc chống nôn": "Thuốc chống nôn theo chỉ định/tư vấn y tế",
    "thuốc điều trị dạ dày": "Thuốc dạ dày/kháng acid theo tư vấn y tế",
    "thuốc giảm đau nha khoa": "Thuốc giảm đau thông thường theo tư vấn; cần khám nha khoa để xử lý nguyên nhân",
}

DIAGNOSIS_VI = {
    "injury to the leg": "Chấn thương/viêm vùng chân (tham khảo)",
    "otitis media": "Viêm tai giữa (tham khảo)",
    "dental caries": "Sâu răng (tham khảo)",
    "gum disease": "Bệnh nướu/viêm nướu (tham khảo)",
}

VI_SYMPTOM_KEYWORDS = {
    "itching": ["ngứa", "ngứa da"],
    "skin_rash": ["phát ban", "nổi ban", "mẩn đỏ", "nổi mẩn", "ban đỏ"],
    "nodal_skin_eruptions": ["nổi nốt trên da", "sẩn da", "nốt da"],
    "continuous_sneezing": ["hắt hơi", "hắt hơi liên tục", "nhảy mũi", "nhảy mũi liên tục"],
    "shivering": ["run rẩy", "rét run", "run lạnh"],
    "chills": ["ớn lạnh", "lạnh run", "rét"],
    "joint_pain": ["đau khớp", "nhức khớp"],
    "stomach_pain": ["đau dạ dày", "đau bao tử", "đau thượng vị"],
    "acidity": ["ợ chua", "trào ngược", "nóng rát dạ dày"],
    "ulcers_on_tongue": ["loét lưỡi", "lở lưỡi"],
    "muscle_wasting": ["teo cơ", "mất cơ"],
    "vomiting": ["nôn", "nôn ói", "buồn nôn và nôn"],
    "burning_micturition": ["tiểu buốt", "tiểu rát", "đái buốt"],
    "spotting_ urination": ["tiểu lắt nhắt", "đái rắt", "tiểu rắt", "tiểu nhắt"],
    "fatigue": ["mệt mỏi", "mệt", "đuối sức"],
    "weight_gain": ["tăng cân"],
    "anxiety": ["lo âu", "bồn chồn", "hồi hộp lo lắng"],
    "cold_hands_and_feets": ["tay chân lạnh", "bàn tay lạnh", "bàn chân lạnh"],
    "mood_swings": ["thay đổi tâm trạng", "tâm trạng thất thường"],
    "weight_loss": ["sụt cân", "giảm cân"],
    "restlessness": ["bứt rứt", "không yên"],
    "lethargy": ["lừ đừ", "uể oải", "li bì nhẹ"],
    "patches_in_throat": ["mảng trong họng", "đốm trong họng"],
    "irregular_sugar_level": ["đường huyết bất thường", "đường máu bất thường"],
    "cough": ["ho", "ho khan", "ho nhiều"],
    "high_fever": ["sốt cao", "sốt 39", "sốt 40", "sốt trên 39"],
    "mild_fever": ["sốt nhẹ", "sốt 37", "sốt 38"],
    "sunken_eyes": ["mắt trũng"],
    "breathlessness": ["khó thở", "hụt hơi", "thở gấp"],
    "sweating": ["đổ mồ hôi", "vã mồ hôi"],
    "dehydration": ["mất nước", "khô môi", "khát nước nhiều"],
    "indigestion": ["khó tiêu", "đầy bụng"],
    "headache": ["đau đầu", "nhức đầu"],
    "yellowish_skin": ["vàng da"],
    "dark_urine": ["nước tiểu sẫm", "tiểu sẫm màu", "nước tiểu đậm"],
    "nausea": ["buồn nôn", "nôn nao"],
    "loss_of_appetite": ["chán ăn", "ăn kém"],
    "pain_behind_the_eyes": ["đau sau mắt", "đau hốc mắt"],
    "back_pain": ["đau lưng"],
    "constipation": ["táo bón", "không đi cầu được", "không đi đại tiện được", "khó đi đại tiện",
                     "phân khô cứng", "phân cứng", "rặn khó", "nhiều ngày không đi ngoài", "mấy ngày không đi cầu"],
    "abdominal_pain": ["đau bụng", "bụng đau", "đau vùng bụng", "đau quặn bụng", "bụng đau quặn"],
    "diarrhoea": ["tiêu chảy", "đi ngoài phân lỏng", "đi ngoài lỏng", "đi phân lỏng"],
    "yellow_urine": ["nước tiểu vàng", "tiểu vàng"],
    "yellowing_of_eyes": ["vàng mắt", "mắt vàng"],
    "acute_liver_failure": ["suy gan cấp"],
    "fluid_overload": ["quá tải dịch", "ứ dịch"],
    "fluid_overload.1": ["quá tải dịch", "ứ dịch"],
    "swelling_of_stomach": ["bụng sưng", "bụng chướng"],
    "swelled_lymph_nodes": ["sưng hạch", "nổi hạch"],
    "malaise": ["khó chịu", "mệt lả"],
    "blurred_and_distorted_vision": ["nhìn mờ", "mờ mắt"],
    "phlegm": ["đờm", "có đờm", "ho đờm"],
    "throat_irritation": ["rát họng", "ngứa họng"],
    "sore throat": ["đau họng", "rát họng", "viêm họng"],
    "throat pain": ["đau họng"],
    "pain in the throat": ["đau họng"],
    "dry sore throat": ["khô họng", "đau họng khô"],
    "severe throat pain": ["đau họng nặng", "đau họng dữ dội"],
    "significant throat pain": ["đau họng nhiều"],
    "throat discomfort": ["khó chịu họng"],
    "irritation in the throat": ["rát họng", "ngứa họng"],
    "itching in the throat": ["ngứa họng"],
    "itchy throat": ["ngứa họng"],
    "redness_of_eyes": ["đỏ mắt", "mắt đỏ"],
    "sinus_pressure": ["đau xoang", "tức xoang"],
    "runny_nose": ["sổ mũi", "chảy nước mũi"],
    "congestion": ["nghẹt mũi", "tắc mũi"],
    "chest_pain": ["đau ngực", "tức ngực"],
    "weakness_in_limbs": ["yếu tay chân", "yếu chi"],
    "fast_heart_rate": ["tim đập nhanh", "mạch nhanh"],
    "pain_during_bowel_movements": ["đau khi đi ngoài", "đau khi đại tiện"],
    "pain_in_anal_region": ["đau hậu môn"],
    "bloody_stool": ["đi ngoài ra máu", "phân máu"],
    "irritation_in_anus": ["ngứa hậu môn", "kích ứng hậu môn"],
    "neck_pain": ["đau cổ", "đau gáy"],
    "dizziness": ["chóng mặt", "hoa mắt", "choáng", "choáng váng"],
    "cramps": ["chuột rút", "co rút cơ"],
    "bruising": ["bầm tím", "vết bầm"],
    "obesity": ["béo phì", "thừa cân"],
    "swollen_legs": ["sưng chân", "phù chân"],
    "swollen_blood_vessels": ["mạch máu sưng", "tĩnh mạch sưng"],
    "puffy_face_and_eyes": ["mặt phù", "mắt phù", "sưng mặt"],
    "enlarged_thyroid": ["bướu cổ", "tuyến giáp to"],
    "brittle_nails": ["móng giòn", "móng dễ gãy", "móng tay giòn", "móng tay dễ gãy", "móng giòn dễ gãy", "móng tay giòn dễ gãy"],
    "swollen_extremeties": ["sưng tay chân", "phù chi"],
    "excessive_hunger": ["đói nhiều", "ăn nhiều"],
    "extra_marital_contacts": ["quan hệ ngoài luồng", "quan hệ tình dục nguy cơ"],
    "drying_and_tingling_lips": ["khô môi", "tê môi"],
    "slurred_speech": ["nói khó", "nói líu", "nói đớ"],
    "knee_pain": ["đau gối", "đau khớp gối"],
    "hip_joint_pain": ["đau khớp háng", "đau hông"],
    "muscle_weakness": ["yếu cơ"],
    "stiff_neck": ["cứng cổ", "cứng gáy"],
    "swelling_joints": ["sưng khớp"],
    "movement_stiffness": ["cứng khi vận động", "cứng vận động"],
    "spinning_movements": ["chóng mặt xoay", "cảm giác quay cuồng"],
    "loss_of_balance": ["mất thăng bằng"],
    "unsteadiness": ["đi không vững", "loạng choạng"],
    "weakness_of_one_body_side": ["yếu nửa người", "liệt nửa người"],
    "loss_of_smell": ["mất khứu giác", "mất mùi"],
    "bladder_discomfort": ["khó chịu bàng quang", "đau bàng quang"],
    "foul_smell_of urine": ["nước tiểu hôi", "tiểu hôi"],
    "continuous_feel_of_urine": ["cảm giác muốn tiểu liên tục", "mắc tiểu liên tục"],
    "passage_of_gases": ["xì hơi nhiều", "đầy hơi"],
    "internal_itching": ["ngứa bên trong"],
    "toxic_look_(typhos)": ["vẻ nhiễm độc", "nhiễm độc"],
    "depression": ["trầm cảm", "buồn bã kéo dài"],
    "irritability": ["dễ cáu", "cáu gắt"],
    "muscle_pain": ["đau cơ", "nhức mỏi cơ"],
    "altered_sensorium": ["rối loạn ý thức", "lơ mơ"],
    "red_spots_over_body": ["đốm đỏ toàn thân", "chấm đỏ trên da"],
    "belly_pain": ["đau bụng dưới"],
    "abnormal_menstruation": ["kinh nguyệt bất thường", "rối loạn kinh nguyệt"],
    "dischromic _patches": ["mảng đổi màu da", "da đổi màu"],
    "dischromic patches": ["mảng đổi màu da", "da đổi màu"],
    "watering_from_eyes": ["chảy nước mắt", "mắt chảy nước"],
    "increased_appetite": ["tăng cảm giác thèm ăn", "ăn nhiều"],
    "polyuria": ["tiểu nhiều", "đái nhiều"],
    "family_history": ["tiền sử gia đình"],
    "mucoid_sputum": ["đờm nhầy", "đàm nhầy"],
    "rusty_sputum": ["đờm màu gỉ sắt", "đàm gỉ sắt"],
    "lack_of_concentration": ["kém tập trung", "giảm tập trung"],
    "visual_disturbances": ["rối loạn thị giác", "nhìn bất thường", "sợ ánh sáng", "nhạy cảm ánh sáng", "sợ tiếng ồn", "nhạy cảm tiếng ồn"],
    "receiving_blood_transfusion": ["truyền máu"],
    "receiving_unsterile_injections": ["tiêm không vô trùng", "tiêm bẩn"],
    "coma": ["hôn mê"],
    "stomach_bleeding": ["xuất huyết dạ dày", "chảy máu dạ dày"],
    "distention_of_abdomen": ["chướng bụng", "bụng căng"],
    "history_of_alcohol_consumption": ["uống rượu", "nghiện rượu", "tiền sử rượu"],
    "blood_in_sputum": ["ho ra máu", "đờm có máu"],
    "prominent_veins_on_calf": ["tĩnh mạch nổi ở bắp chân", "gân xanh bắp chân"],
    "palpitations": ["đánh trống ngực", "hồi hộp"],
    "painful_walking": ["đau khi đi bộ", "đi lại đau"],
    "pus_filled_pimples": ["mụn mủ"],
    "blackheads": ["mụn đầu đen"],
    "scurring": ["sẹo", "sẹo mụn"],
    "skin_peeling": ["bong tróc da", "da bong tróc", "tróc da", "da tróc"],
    "silver_like_dusting": ["vảy bạc", "vảy trắng bạc"],
    "small_dents_in_nails": ["lõm móng", "rỗ móng"],
    "inflammatory_nails": ["viêm móng"],
    "blister": ["mụn nước", "bọng nước"],
    "red_sore_around_nose": ["loét đỏ quanh mũi", "đỏ đau quanh mũi"],
    "yellow_crust_ooze": ["chảy dịch vàng", "đóng vảy vàng"],
    "fever": ["sốt"],
    "insomnia": ["mất ngủ", "khó ngủ", "ngủ không được", "ngủ kém", "trằn trọc", "thức giấc nhiều"],
    "toothache": ["đau răng", "nhức răng", "răng đau"],
    "gum pain": ["đau nướu", "đau lợi", "nướu đau", "lợi đau"],
    "pain in gums": ["đau nướu", "đau lợi", "nướu đau", "lợi đau"],
    "jaw swelling": ["sưng hàm", "sưng vùng hàm", "sưng mặt do răng"],
    "bleeding gums": ["chảy máu nướu", "chảy máu lợi", "nướu chảy máu", "lợi chảy máu"],
    # Bổ sung 2026-06-08: tăng độ phủ hô hấp / tiêu hóa / tiết niệu (feature có thật trong model)
    "wheezing": ["khò khè", "thở rít", "thở khò khè"],
    "chest tightness": ["tức ngực", "nặng ngực", "đè nặng ngực"],
    "heartburn": ["ợ nóng", "nóng rát thượng vị", "nóng rát sau xương ức"],
    "melena": ["phân đen", "đi ngoài phân đen", "phân hắc ín"],
    "vomiting blood": ["nôn ra máu", "ói ra máu", "nôn ra máu tươi"],
    "painful urination": ["tiểu đau", "đau khi đi tiểu", "đau khi tiểu"],
    "retention of urine": ["bí tiểu", "không tiểu được"],
    "low urine output": ["tiểu ít", "lượng nước tiểu ít"],
    "frontal headache": ["đau đầu vùng trán", "đau trán"],
}

# Bổ sung 2026-06-09 (robust hoá tiếng Việt): các cụm tiếng Việt phổ biến còn thiếu,
# map sang feature CÓ THẬT trong model. Merge để không trùng/đè key cũ.
_VI_SYMPTOM_KEYWORDS_EXTRA = {
    "headache": ["đau nửa đầu", "đau nửa đầu từng cơn", "nhức nửa đầu", "nhức một bên đầu",
                 "đau nhức nửa đầu", "nhức đầu theo nhịp mạch", "đau đầu theo nhịp mạch"],
    "stomach_pain": ["đau thượng vị lúc đói", "đau vùng thượng vị"],
    "heartburn": ["nóng rát thượng vị", "nóng rát vùng thượng vị", "ợ nóng"],
    "acidity": ["hay ợ chua", "ợ hơi"],
    "vomiting": ["nôn nhiều", "nôn nhiều lần", "nôn liên tục"],
    "diarrhoea": ["đi ngoài liên tục", "đi ngoài cả ngày", "đi ngoài nhiều lần", "đi ngoài phân lỏng nước",
                  "đi ngoài tóe nước", "tiêu chảy tóe nước", "đi ngoài nhiều nước", "đi ngoài như nước", "tiêu chảy nhiều lần"],
    "dehydration": ["khát nước nhiều", "khát nhiều"],
    "neck_pain": ["đau vai gáy", "đau cổ gáy", "nhức vai gáy"],
    "back_pain": ["đau lưng dưới", "đau thắt lưng"],
    "painful menstruation": ["đau bụng kinh", "đau bụng kinh dữ dội", "đau quặn kỳ kinh", "thống kinh"],
    "skin_rash": ["mề đay", "nổi mề đay", "mẩn ngứa"],
    "itching": ["ngứa khắp người", "ngứa nhiều"],
    "dischromic patches": ["mảng đỏ hình tròn", "mảng đỏ tròn"],
    "skin_peeling": ["bong vảy", "bong vảy dày", "bong tróc vảy"],
    "blister": ["mụn nước thành chùm", "nổi bóng nước", "bóng nước"],
    "sinus_pressure": ["đau nhức xoang", "đau xoang má", "nhức xoang"],
    "wheezing": ["khò khè khi gắng sức", "thở khò khè"],
    "breathlessness": ["lên cơn khó thở", "khó thở khi gắng sức", "khó thở khi gặp lạnh"],
    "enlarged_thyroid": ["bướu cổ to", "bướu giáp", "cổ to", "cổ phình", "cổ bạnh", "mắt lồi", "lồi mắt"],
    "excessive_urination_at_night": ["tiểu đêm", "tiểu đêm nhiều lần"],
    "excessive_hunger": ["đói nhiều"],
    "chills": ["rét run", "sốt thành cơn"],
    "sweating": ["vã mồ hôi", "ra nhiều mồ hôi", "đổ mồ hôi nhiều"],
    "bloody_stool": ["phân có máu", "đi ngoài ra máu", "đi ngoài máu nhầy", "phân máu nhầy"],
    # An toàn / thần kinh:
    "seizures": ["co giật", "co giật sùi bọt mép", "lên cơn co giật"],
    "altered_sensorium": ["mất ý thức", "lơ mơ", "rối loạn ý thức", "lú lẫn"],
    "stiff_neck": ["cổ cứng", "gáy cứng"],
    "weakness_of_one_body_side": ["méo miệng", "yếu một bên", "yếu nửa người", "liệt nửa người",
                                   "tay chân một bên yếu", "liệt một bên", "yếu hẳn một bên người", "tê yếu một bên"],
    "slurred_speech": ["nói ngọng", "nói khó", "líu lưỡi"],
    "paresthesia": ["tê bì", "châm chích", "tê rần"],
    "muscle_pain": ["đau mỏi toàn thân", "đau nhức toàn thân", "đau người", "đau mỏi người"],
    "Redness, swelling, discharge from the wound": ["chảy mủ", "vết thương chảy mủ", "vết thương sưng đỏ", "mưng mủ", "có mủ"],
    "Shooting or burning pain, tingling or numbness": ["đau rát bỏng lan dọc dây thần kinh", "đau lan dọc dây thần kinh", "đau rát bỏng lan"],
    # Batch 3: cơ-xương-khớp / lo âu / tim mạch
    "joint_pain": ["khớp sưng đau", "sưng đau khớp", "viêm khớp", "viêm gân", "đau gân", "ngón chân sưng đau", "sưng đỏ đau khớp"],
    "anxiety": ["sợ hãi vô cớ", "hoảng sợ", "lo lắng quá mức", "căng thẳng", "lo âu kéo dài"],
    "chest_pain": ["đau thắt ngực", "đau ngực khi gắng sức", "đau ngực bóp nghẹt"],
    "palpitations": ["tim đập nhanh", "tim đập mạnh", "tim đập không đều", "loạn nhịp", "trống ngực"],
    "High blood pressure, chest pain or discomfort, shortness of breath, fatigue":
        ["huyết áp cao", "cao huyết áp", "tăng huyết áp", "huyết áp 160", "huyết áp lên cao"],
}
for _k, _v in _VI_SYMPTOM_KEYWORDS_EXTRA.items():
    VI_SYMPTOM_KEYWORDS[_k] = list(dict.fromkeys(VI_SYMPTOM_KEYWORDS.get(_k, []) + _v))

UNSUPPORTED_SYMPTOM_KEYWORDS = {
    "sleep_problem": {
        "label_vi": "Mất ngủ/khó ngủ",
        "phrases": [
            "mất ngủ",
            "khó ngủ",
            "ngủ không được",
            "ngủ kém",
            "trằn trọc",
            "thức giấc nhiều",
        ],
    }
}


AUTO_EXACT_SYMPTOM_KEYWORDS = {
    "chest tightness": ["tức ngực", "nặng ngực", "căng tức ngực"],
    "diarrhea": ["tiêu chảy", "đi ngoài phân lỏng"],
    "difficulty breathing": ["khó thở", "thở khó", "hụt hơi"],
    "shortness of breath": ["khó thở", "hụt hơi"],
    "breathing fast": ["thở nhanh"],
    "abnormal breathing sounds": ["tiếng thở bất thường", "khò khè"],
    "wheezing": ["khò khè", "thở rít"],
    "coughing up sputum": ["ho có đờm", "khạc đờm"],
    "coryza": ["sổ mũi", "chảy nước mũi"],
    "hoarse voice": ["khàn tiếng"],
    "difficulty in swallowing": ["khó nuốt", "nuốt khó"],
    "difficulty swallowing": ["khó nuốt", "nuốt khó"],
    "heartburn": ["ợ nóng", "nóng rát sau xương ức"],
    "acidic taste": ["vị chua trong miệng"],
    "decreased appetite": ["chán ăn", "ăn kém"],
    "excessive thirst": ["khát nhiều"],
    "frequent urination": ["tiểu nhiều", "đi tiểu thường xuyên"],
    "blood in urine": ["tiểu ra máu", "nước tiểu có máu"],
    "blood in stool": ["đi ngoài ra máu", "phân có máu", "phân nhầy máu", "phân có nhầy máu", "đi ngoài phân nhầy máu"],
    "changes in stool appearance": ["thay đổi tính chất phân", "phân bất thường"],
    "diminished hearing": ["giảm thính lực", "nghe kém"],
    "diminished vision": ["giảm thị lực", "nhìn kém"],
    "double vision": ["nhìn đôi"],
    "blindness": ["mù", "mất thị lực"],
    "eye redness": ["đỏ mắt", "mắt đỏ"],
    "foreign body sensation in eye": ["cộm mắt", "cảm giác dị vật trong mắt"],
    "fluid in ear": ["dịch trong tai", "chảy dịch tai"],
    "fainting": ["ngất", "xỉu"],
    "delusions or hallucinations": ["hoang tưởng", "ảo giác"],
    "disturbance of memory": ["rối loạn trí nhớ", "giảm trí nhớ"],
    "drug abuse": ["lạm dụng thuốc", "lạm dụng chất"],
    "abusing alcohol": ["lạm dụng rượu", "uống rượu nhiều"],
    "ache all over": ["đau nhức toàn thân", "đau mỏi toàn thân"],
    "allergic reaction": ["dị ứng", "phản ứng dị ứng"],
    "abnormal appearing skin": ["da bất thường", "bất thường trên da"],
    "abnormal involuntary movements": ["cử động không tự chủ", "vận động bất thường"],
    "abnormal movement of eyelid": ["mí mắt co giật", "cử động mí mắt bất thường"],
    "acne or pimples": ["mụn trứng cá", "mụn bọc", "mụn mủ"],
    "back cramps or spasms": ["co thắt lưng", "chuột rút lưng"],
    "blood clots during menstrual periods": ["máu cục khi hành kinh", "kinh nguyệt có máu cục"],
    "diaper rash": ["hăm tã"],
    "dischromic patches": ["mảng đổi màu da", "da đổi màu", "mảng trắng loang", "da loang màu", "loang da"],
    "easy bruising": ["dễ bầm tím", "dễ xuất hiện vết bầm"],
    "elevated intraocular pressure": ["tăng nhãn áp", "áp lực mắt tăng"],
    "excessive anger": ["dễ tức giận", "giận dữ quá mức"],
    "excessive body weight": ["thừa cân", "béo phì"],
    "excessive daytime sleepiness": ["buồn ngủ ban ngày nhiều", "ngủ gà ban ngày"],
    "excessive sweating": ["đổ mồ hôi nhiều", "tăng tiết mồ hôi"],
    "excessive urination at night": ["tiểu đêm nhiều", "đi tiểu nhiều ban đêm"],
    "excessive worrying": ["lo lắng quá mức", "lo âu nhiều"],
    "eyelid lesion or rash": ["tổn thương mí mắt", "phát ban mí mắt"],
    "feeling ill": ["cảm thấy mệt", "khó chịu trong người"],
    "flu-like syndrome": ["triệu chứng giống cúm", "hội chứng giống cúm"],
    "fluid retention": ["giữ nước", "ứ dịch", "phù"],
    "focal weakness": ["yếu khu trú", "yếu một vùng cơ thể"],
    "frontal headache": ["đau đầu vùng trán", "đau trán"],
    "hemoptysis": ["ho ra máu"],
    "hot flashes": ["bốc hỏa"],
    "foul smell of urine": ["nước tiểu hôi", "tiểu hôi"],
    "hurts to breath": ["đau khi thở", "thở đau"],
    "increased heart rate": ["tim đập nhanh", "mạch nhanh"],
    "infant feeding problem": ["trẻ bú kém", "vấn đề ăn bú ở trẻ"],
    "infertility": ["vô sinh", "hiếm muộn"],
    "intermenstrual bleeding": ["ra máu giữa kỳ kinh", "chảy máu giữa chu kỳ"],
    "involuntary urination": ["tiểu không tự chủ", "són tiểu"],
    "irregular heartbeat": ["nhịp tim không đều", "loạn nhịp"],
    "itchiness of eye": ["ngứa mắt"],
    "itching of skin": ["ngứa da"],
    "itching of the anus": ["ngứa hậu môn"],
    "itchy ear(s)": ["ngứa tai"],
    "itchy scalp": ["ngứa da đầu"],
    "jaundice": ["vàng da", "vàng mắt"],
    "lacrimation": ["chảy nước mắt"],
    "lip swelling": ["sưng môi"],
    "loss of sensation": ["mất cảm giác", "giảm cảm giác"],
    "low self-esteem": ["tự ti", "mặc cảm"],
    "low urine output": ["tiểu ít", "lượng nước tiểu ít"],
    "melena": ["đi ngoài phân đen", "phân đen"],
    "mouth ulcer": ["loét miệng", "lở miệng"],
}

AUTO_BODY_PARTS = {
    "abdomen": ["bụng"],
    "abdominal": ["bụng"],
    "belly": ["bụng"],
    "stomach": ["dạ dày"],
    "back": ["lưng"],
    "chest": ["ngực"],
    "ribcage": ["lồng ngực"],
    "head": ["đầu"],
    "ear": ["tai"],
    "eye": ["mắt"],
    "eyelid": ["mí mắt"],
    "face": ["mặt"],
    "facial": ["mặt"],
    "jaw": ["hàm"],
    "mouth": ["miệng"],
    "gum": ["nướu", "lợi"],
    "gums": ["nướu", "lợi"],
    "tooth": ["răng"],
    "throat": ["họng"],
    "neck": ["cổ", "gáy"],
    "arm": ["tay", "cánh tay"],
    "elbow": ["khuỷu tay"],
    "hand": ["bàn tay"],
    "finger": ["ngón tay"],
    "hip": ["hông"],
    "knee": ["gối"],
    "ankle": ["cổ chân", "mắt cá chân"],
    "foot": ["bàn chân"],
    "toe": ["ngón chân"],
    "leg": ["chân"],
    "shoulder": ["vai"],
    "breast": ["vú"],
    "pelvic": ["vùng chậu"],
    "groin": ["bẹn"],
    "flank": ["hông lưng"],
}
